version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    resource_class: small
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - "a6:2c:59:70:52:62:77:34:61:2d:01:a4:5e:c1:b3:10"
      - run:
          name: Add Hosts
          command: ssh-keyscan -H $SERVER >> ~/.ssh/known_hosts
      - run:
          name: Upload files
          command: scp * $USER@$SERVER:~/.qqbot-tmp/plugins/
      - run:
          name: Replug plugin
          command: bash .circleci/update_plugin.sh